import {WEAPONS} from '../../data/weapons.js';
import {ENEMIES,ELITES,BOSSES} from '../../data/content.js';
export class Gameplay{
constructor(canvas,ctx,opts){this.canvas=canvas;this.ctx=ctx;this.opts=opts;this.time=opts.duration*60;this.elapsed=0;this.spawnClock=0;this.fireClock=0;this.level=1;this.xp=0;this.xpNeed=18;this.kills=0;this.currency=0;this.jp=0;this.paused=false;this.ended=false;this.extraction=false;this.extractTimer=12;this.player={x:canvas.width/2,y:canvas.height/2,r:12,hp:opts.hp,maxHp:opts.hp,speed:opts.speed,armor:opts.armor||0};this.enemies=[];this.projectiles=[];this.pickups=[];this.particles=[];this.weapons=[{...WEAPONS.find(w=>w.id===opts.weapon),level:1}];this.boss=null;this.onLevel=()=>{};this.onEnd=()=>{};this.onBoss=()=>{};}
resize(w,h){this.canvas.width=w;this.canvas.height=h}
spawn(){const phase=this.elapsed/(this.opts.duration*60);const elite=Math.random()<Math.max(0,(phase-.18)*.06);const angle=Math.random()*Math.PI*2,dist=Math.max(this.canvas.width,this.canvas.height)*.62+90;const x=this.player.x+Math.cos(angle)*dist,y=this.player.y+Math.sin(angle)*dist;const type=elite?ELITES[Math.floor(Math.random()*ELITES.length)]:ENEMIES[Math.min(ENEMIES.length-1,Math.floor(phase*ENEMIES.length))];const hp=(elite?130:24)*(1+phase*4)*(1+(this.opts.difficulty||0)*.24);this.enemies.push({x,y,r:elite?16:10,hp,maxHp:hp,speed:(elite?74:55)+phase*38,type,elite,flash:0})}
spawnBoss(){if(this.boss)return;const name=BOSSES[Math.min(BOSSES.length-1,Math.floor((this.opts.duration-5)/10))];this.boss={x:this.player.x+340,y:this.player.y-240,r:48,hp:1600+this.opts.duration*90,maxHp:1600+this.opts.duration*90,name,phase:1,shot:0};this.onBoss(this.boss)}
update(dt,input){if(this.paused||this.ended)return;this.elapsed+=dt;if(!this.extraction){this.time=Math.max(0,this.time-dt);if(this.time<=0){this.extraction=true;this.extractTimer=10}}else{this.extractTimer-=dt;if(this.extractTimer<=0){this.ended=true;this.onEnd(true);return}}
const v=input.vector();this.player.x+=v.x*this.player.speed*dt;this.player.y+=v.y*this.player.speed*dt;this.player.x=Math.max(20,Math.min(this.canvas.width-20,this.player.x));this.player.y=Math.max(20,Math.min(this.canvas.height-20,this.player.y));const phase=this.elapsed/(this.opts.duration*60);this.spawnClock-=dt;const maxEnemies=this.opts.performance?90:180;if(this.spawnClock<=0&&this.enemies.length<maxEnemies){this.spawn();this.spawnClock=Math.max(.08,.62-phase*.48)/(1+(this.opts.difficulty||0)*.18)}if(!this.boss&&this.time<Math.min(55,this.opts.duration*60*.12))this.spawnBoss();this.fireClock-=dt;if(this.fireClock<=0){this.fire();this.fireClock=this.weapons[0].cooldown*Math.pow(.93,this.weapons[0].level-1)}
for(const p of this.projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}this.projectiles=this.projectiles.filter(p=>p.life>0);for(const e of this.enemies){const dx=this.player.x-e.x,dy=this.player.y-e.y,m=Math.hypot(dx,dy)||1;e.x+=dx/m*e.speed*dt;e.y+=dy/m*e.speed*dt;e.flash=Math.max(0,e.flash-dt);if(m<e.r+this.player.r){this.player.hp-=Math.max(1,10-this.player.armor)*dt;if(this.player.hp<=0){this.ended=true;this.onEnd(false);return}}}
for(const p of this.projectiles){for(const e of this.enemies){if(e.hp<=0)continue;if(Math.hypot(p.x-e.x,p.y-e.y)<p.r+e.r){e.hp-=p.damage;e.flash=.08;p.life=0;if(e.hp<=0)this.kill(e)}}if(this.boss&&Math.hypot(p.x-this.boss.x,p.y-this.boss.y)<p.r+this.boss.r){this.boss.hp-=p.damage;p.life=0;if(this.boss.hp<=0){this.jp+=25;this.currency+=180;this.boss=null}}}
this.enemies=this.enemies.filter(e=>e.hp>0);for(const q of this.pickups){if(Math.hypot(q.x-this.player.x,q.y-this.player.y)<90){const dx=this.player.x-q.x,dy=this.player.y-q.y,m=Math.hypot(dx,dy)||1;q.x+=dx/m*360*dt;q.y+=dy/m*360*dt}if(Math.hypot(q.x-this.player.x,q.y-this.player.y)<18){q.dead=true;this.addXP(q.value)}}this.pickups=this.pickups.filter(q=>!q.dead);if(this.boss){const dx=this.player.x-this.boss.x,dy=this.player.y-this.boss.y,m=Math.hypot(dx,dy)||1;this.boss.x+=dx/m*32*dt;this.boss.y+=dy/m*32*dt;this.boss.shot-=dt;if(this.boss.shot<=0){this.boss.shot=1.5;this.player.hp-=Math.max(2,16-this.player.armor)}}}
fire(){let target=null,best=Infinity;for(const e of this.enemies){const d=(e.x-this.player.x)**2+(e.y-this.player.y)**2;if(d<best){best=d;target=e}}if(!target&&this.boss)target=this.boss;if(!target)return;const dx=target.x-this.player.x,dy=target.y-this.player.y,m=Math.hypot(dx,dy)||1;const count=this.weapons[0].level>=3?2:1;for(let i=0;i<count;i++){const spread=(i-(count-1)/2)*.12;const a=Math.atan2(dy,dx)+spread;this.projectiles.push({x:this.player.x,y:this.player.y,vx:Math.cos(a)*520,vy:Math.sin(a)*520,r:3,damage:this.weapons[0].damage*(1+(this.weapons[0].level-1)*.2),life:1.3})}}
kill(e){this.kills++;this.currency+=e.elite?8:1;if(e.elite)this.jp+=3;this.pickups.push({x:e.x,y:e.y,r:5,value:e.elite?7:2})}
addXP(v){this.xp+=v;while(this.xp>=this.xpNeed){this.xp-=this.xpNeed;this.level++;this.xpNeed=Math.floor(this.xpNeed*1.17+5);this.paused=true;this.onLevel(this.level);break}}
upgrade(kind){if(kind==='weapon')this.weapons[0].level=Math.min(8,this.weapons[0].level+1);if(kind==='speed')this.player.speed*=1.09;if(kind==='armor')this.player.armor+=1;if(kind==='heal')this.player.hp=Math.min(this.player.maxHp,this.player.hp+28);this.paused=false}
draw(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.fillStyle=this.opts.mapColor||'#10262d';c.fillRect(0,0,w,h);c.strokeStyle='rgba(118,231,212,.06)';c.lineWidth=1;for(let x=0;x<w;x+=64){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<h;y+=64){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}for(const q of this.pickups){c.fillStyle='#7df7e1';c.beginPath();c.arc(q.x,q.y,5,0,Math.PI*2);c.fill()}for(const p of this.projectiles){c.fillStyle='#ffe189';c.beginPath();c.arc(p.x,p.y,p.r,0,Math.PI*2);c.fill()}for(const e of this.enemies){c.fillStyle=e.flash?'#ffffff':e.elite?'#ff8a68':'#9ab1b5';c.beginPath();c.arc(e.x,e.y,e.r,0,Math.PI*2);c.fill();if(e.elite){c.strokeStyle='#ff7068';c.stroke()}}if(this.boss){c.fillStyle='#8e2630';c.beginPath();c.arc(this.boss.x,this.boss.y,this.boss.r,0,Math.PI*2);c.fill();c.strokeStyle='#ff7068';c.lineWidth=3;c.stroke()}c.fillStyle='#76e7d4';c.beginPath();c.arc(this.player.x,this.player.y,this.player.r,0,Math.PI*2);c.fill();c.strokeStyle='#d8fff8';c.stroke();if(this.extraction){c.strokeStyle='#f5d27a';c.lineWidth=4;c.beginPath();c.arc(w*.84,h*.2,28+Math.sin(this.elapsed*5)*5,0,Math.PI*2);c.stroke();c.fillStyle='#f5d27a';c.font='12px monospace';c.fillText('EXTRACTION',w*.84-42,h*.2+50)}}}
