import {Gameplay} from './gameplay.js';
const COLORS={'Patrol Scout':'#718d7e','Rifle Cell':'#879b91','Shield Trooper':'#b09b65','Longshot Sniper':'#92758d','Breacher Heavy':'#a7604c','Signal Jammer':'#806ca7','Veil Operative':'#617b86','Augment Marauder':'#b54d45','Mortar Team':'#9a835b'};
export class PolishedGameplay extends Gameplay{
constructor(canvas,ctx,opts){super(canvas,ctx,opts);this.player.speed*=.68;this.player.r*=1.12}
update(dt,input){super.update(dt,input);if(this.paused||this.ended)return;this.separateSwarm(dt);this.keepPersonalSpace(dt)}
separateSwarm(dt){const es=this.enemies,limit=Math.min(es.length,180);for(let i=0;i<limit;i++){const a=es[i];let sx=0,sy=0,h=0;for(let j=0;j<limit;j++){if(i===j)continue;const b=es[j],dx=a.x-b.x,dy=a.y-b.y,d2=dx*dx+dy*dy,min=(a.r+b.r)*2.05;if(d2>0&&d2<min*min){const d=Math.sqrt(d2),p=(min-d)/min;sx+=dx/d*p;sy+=dy/d*p;h++}}if(h){a.x+=sx/h*185*dt;a.y+=sy/h*185*dt}}}
keepPersonalSpace(dt){const p=this.player;for(const e of this.enemies){const dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy)||1,min=p.r+e.r+5;if(d<min){const push=(min-d)*8*dt;e.x+=dx/d*push;e.y+=dy/d*push}}}
drawWorld(c,w,h){const map=this.opts.mapId||'blacksite';c.fillStyle=map==='arctic'?'#18303b':map==='sunken'?'#0b3033':'#0c252d';c.fillRect(0,0,w,h);c.strokeStyle='rgba(118,231,212,.045)';for(let x=0;x<w;x+=96){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<h;y+=96){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}if(map==='blacksite'){c.strokeStyle='rgba(255,190,78,.16)';c.lineWidth=2;for(let y=240;y<h;y+=430){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();for(let x=0;x<w;x+=34){c.beginPath();c.moveTo(x,y-6);c.lineTo(x+12,y+6);c.stroke()}}}for(const d of this.decor){c.save();c.translate(d.x,d.y);c.fillStyle='rgba(5,15,19,.36)';c.strokeStyle='rgba(120,205,199,.14)';if(d.t===0){c.fillRect(-d.w/2,-d.h/2,d.w,d.h);c.strokeRect(-d.w/2,-d.h/2,d.w,d.h)}else if(d.t===1){c.beginPath();c.arc(0,0,d.w*.28,0,Math.PI*2);c.fill();c.stroke()}else{c.beginPath();c.moveTo(-d.w/2,0);c.lineTo(d.w/2,0);c.stroke()}c.restore()}if(map==='blacksite'){c.font='8px monospace';c.fillStyle='rgba(174,208,207,.13)';c.fillText('SECTOR B-07 // RESTRICTED',18,h*.42);c.fillText('BLACKSITE INTERNAL GRID',w*.55,h*.72)}const g=c.createRadialGradient(w*.5,h*.5,0,w*.5,h*.5,Math.max(w,h)*.7);g.addColorStop(0,'rgba(18,48,55,.03)');g.addColorStop(1,'rgba(0,3,7,.46)');c.fillStyle=g;c.fillRect(0,0,w,h)}
drawPlayer(c,p){const bob=Math.sin(this.elapsed*10)*.8;c.save();c.translate(p.x,p.y);c.rotate(p.angle);c.scale(1.22,1.22);c.translate(0,bob);c.fillStyle='rgba(0,0,0,.42)';c.beginPath();c.ellipse(-2,8,14,7,0,0,Math.PI*2);c.fill();c.strokeStyle='#a8fff4';c.lineWidth=1.5;c.fillStyle=p.hit?'#fff':'#1d5753';c.beginPath();c.arc(-6,0,5.4,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#28635d';c.beginPath();c.moveTo(-1,-7);c.lineTo(10,-5);c.lineTo(11,5);c.lineTo(-1,7);c.closePath();c.fill();c.stroke();c.strokeStyle='#9cf3e8';c.lineWidth=3;c.beginPath();c.moveTo(2,-5);c.lineTo(8,-11);c.moveTo(2,5);c.lineTo(8,11);c.stroke();c.strokeStyle='#dffefa';c.beginPath();c.moveTo(7,-3);c.lineTo(24,-3);c.stroke();c.fillStyle='#fff';c.fillRect(22,-4,6,2);c.fillStyle='#75f5e5';c.beginPath();c.arc(-6,0,2.4,0,Math.PI*2);c.fill();c.strokeStyle='rgba(118,255,235,.55)';c.lineWidth=1;c.beginPath();c.arc(0,0,20,0,Math.PI*2);c.stroke();c.restore()}
drawEnemy(c,e){if(e.type.includes('Drone'))return this.drawDrone(c,e);if(e.type==='Crawler Robot')return this.drawCrawler(c,e);const heavy=e.type==='Breacher Heavy'||e.type==='Augment Marauder',shield=e.type==='Shield Trooper',sniper=e.type==='Longshot Sniper',jammer=e.type==='Signal Jammer',elite=e.elite,col=elite?'#bd4c45':(COLORS[e.type]||'#7c9188'),scale=(heavy?1.35:shield?1.16:sniper?.92:1)*(elite?1.16:1),step=Math.sin(this.elapsed*11+e.phase)*2.4;c.save();c.translate(e.x,e.y);c.rotate(e.angle);c.scale(scale,scale);c.fillStyle='rgba(0,0,0,.38)';c.beginPath();c.ellipse(-2,7,11,5,0,0,Math.PI*2);c.fill();c.fillStyle=e.flash?'#fff':col;c.strokeStyle=elite?'#ff8d82':'rgba(225,238,233,.65)';c.lineWidth=1;c.beginPath();c.arc(-6,0,4.5,0,Math.PI*2);c.fill();c.stroke();c.fillStyle=heavy?'#56352f':'#263a35';c.beginPath();c.moveTo(-1,-6);c.lineTo(9,-5);c.lineTo(10,5);c.lineTo(-1,6);c.closePath();c.fill();c.stroke();c.strokeStyle=col;c.lineWidth=3;c.beginPath();c.moveTo(1,-4);c.lineTo(7,-10-step*.25);c.moveTo(1,4);c.lineTo(7,10+step*.25);c.stroke();c.strokeStyle='#aabbb7';c.lineWidth=2;c.beginPath();c.moveTo(6,-3);c.lineTo(13,-6);c.moveTo(6,3);c.lineTo(13,6);c.stroke();c.strokeStyle=elite?'#ff9a8d':'#d2dfdb';c.lineWidth=2.5;c.beginPath();c.moveTo(9,-2);c.lineTo(sniper?28:21,-2);c.stroke();if(sniper){c.strokeStyle='#b990aa';c.lineWidth=1;c.beginPath();c.moveTo(18,-5);c.lineTo(18,1);c.stroke()}if(shield){c.fillStyle='rgba(200,177,105,.48)';c.strokeStyle='#e0c982';c.beginPath();c.moveTo(15,-9);c.lineTo(22,-6);c.lineTo(22,6);c.lineTo(15,9);c.closePath();c.fill();c.stroke()}if(jammer){c.strokeStyle='#b29ae9';c.beginPath();c.arc(1,0,14+Math.sin(this.elapsed*5+e.phase)*2,0,Math.PI*2);c.stroke()}if(heavy){c.fillStyle='#74483d';c.fillRect(-3,-9,8,4);c.fillRect(-3,5,8,4)}if(elite){c.strokeStyle='rgba(255,91,79,.55)';c.beginPath();c.arc(0,0,17,0,Math.PI*2);c.stroke()}c.restore();this.drawEnemyHealth(c,e,heavy||elite?19:15)}
drawEnemyHealth(c,e,y){if(e.hp>=e.maxHp&&!e.elite)return;const w=e.elite?26:18;c.fillStyle='rgba(1,5,7,.7)';c.fillRect(e.x-w/2,e.y-y,w,3);c.fillStyle=e.elite?'#ff655c':'#b7cec9';c.fillRect(e.x-w/2,e.y-y,w*Math.max(0,e.hp/e.maxHp),3)}
drawDrone(c,e){const col=e.elite?'#ff7468':e.type==='Hunter Drone'?'#e2a65f':'#6fd1d3';c.save();c.translate(e.x,e.y);c.rotate(e.angle);c.fillStyle='#173136';c.strokeStyle=col;c.lineWidth=1.4;c.beginPath();c.moveTo(12,0);c.lineTo(3,-8);c.lineTo(-9,-6);c.lineTo(-12,0);c.lineTo(-9,6);c.lineTo(3,8);c.closePath();c.fill();c.stroke();c.fillStyle=col;c.beginPath();c.arc(2,0,3,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(-3,-7);c.lineTo(-11,-12);c.moveTo(-3,7);c.lineTo(-11,12);c.stroke();c.restore();this.drawEnemyHealth(c,e,16)}
drawCrawler(c,e){const col=e.elite?'#ff7468':'#789ba3',leg=Math.sin(this.elapsed*12+e.phase)*2;c.save();c.translate(e.x,e.y);c.rotate(e.angle);c.fillStyle='#1e3438';c.strokeStyle=col;c.lineWidth=1.3;c.fillRect(-8,-7,16,14);c.strokeRect(-8,-7,16,14);c.beginPath();for(const s of [-1,0,1]){c.moveTo(s*6,-5);c.lineTo(s*8,-13+(s?leg:-leg));c.moveTo(s*6,5);c.lineTo(s*8,13-(s?leg:-leg))}c.stroke();c.fillStyle='#83d4cf';c.fillRect(4,-2,5,4);c.restore();this.drawEnemyHealth(c,e,17)}
}
